spring.application.name=bible-verse-app
spring.datasource.url=jdbc:sqlite:target/bible-verse-app.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
logging.level.root=INFO
logging.level.hu.szegedibibliaszol=DEBUG
app.help.enabled=true
app.database.path=target/bible-verse-app.db

