spring.application.name=bible-verse-app
spring.main.banner-mode=off
spring.datasource.url=jdbc:sqlite:${app.database.path}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
logging.level.root=INFO
logging.level.hu.szegedibibliaszol=DEBUG
app.help.enabled=true
app.database.path=${BIBLE_VERSE_DB_PATH:${user.home}/bible-verses.db}

